# Site settings
title: Slack Tide
email: jeremymv2@gmail.com
url: https://jeremymv2.github.io
description: "\"The brief, calm period between a rising and falling tide.\"  Here I try a hand at pragmatic ramblings about things such as computering, sailing and whatever else."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Slack Tide

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/jeremymv2

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
permalink: pretty
