theme: jekyll-theme-slate
gem "github-pages", group: :jekyll_plugins
title: [The title of your site]
description: [A short description of your site's purpose]
show_downloads: ["true"]
google_analytics: [Your Google Analytics tracking ID]
